// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdIF0xWiz8JktlKZ5fz4tXG9aKDnx6YsM',
    appId: '1:690047837688:web:ba3bf232f01ac84ecce20d',
    messagingSenderId: '690047837688',
    projectId: 'pantone-book',
    authDomain: 'pantone-book.firebaseapp.com',
    storageBucket: 'pantone-book.appspot.com',
    measurementId: 'G-36XZD4B3RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdi9eAG2-7Tuj-3T7rcp1PAQpBv_jQQj4',
    appId: '1:690047837688:android:7d57cda7e5362af0cce20d',
    messagingSenderId: '690047837688',
    projectId: 'pantone-book',
    storageBucket: 'pantone-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcuGSfProJ2lUshgOu8nlT45TaCyk1ibk',
    appId: '1:690047837688:ios:89e9aa9be24aee10cce20d',
    messagingSenderId: '690047837688',
    projectId: 'pantone-book',
    storageBucket: 'pantone-book.appspot.com',
    iosBundleId: 'com.af.pantoneBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcuGSfProJ2lUshgOu8nlT45TaCyk1ibk',
    appId: '1:690047837688:ios:89e9aa9be24aee10cce20d',
    messagingSenderId: '690047837688',
    projectId: 'pantone-book',
    storageBucket: 'pantone-book.appspot.com',
    iosBundleId: 'com.af.pantoneBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdIF0xWiz8JktlKZ5fz4tXG9aKDnx6YsM',
    appId: '1:690047837688:web:0d63efe00309d2a4cce20d',
    messagingSenderId: '690047837688',
    projectId: 'pantone-book',
    authDomain: 'pantone-book.firebaseapp.com',
    storageBucket: 'pantone-book.appspot.com',
    measurementId: 'G-1XCZFV1WFZ',
  );
}
